name: Nightly Builds

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build extension
        run: bun run build

      - name: Build CRX
        run: bun run crx

      - name: Build XPI
        run: bun run xpi

      - name: Upload CRX artifact
        uses: actions/upload-artifact@v4
        with:
          name: crx-extension
          path: builds/*.crx

      - name: Upload XPI artifact
        uses: actions/upload-artifact@v4
        with:
          name: xpi-extension
          path: builds/*.xpi
